spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dev_analytics
    username: postgres
    password: 123
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  security:
    jwt:
      secret: "3069dca7dcfb855b274fe98bab084cf4879927e3edcf440004ec76f029d560f5"
app:
  jwt:
    secret: "3069dca7dcfb855b274fe98bab084cf4879927e3edcf440004ec76f029d560f5"
    expiration: 3600000
server:
  port: 8080
logging:
  level:
    com.juliashtal: DEBUG
