package com.juliashtal.devanalytics.metrics.model;

public enum MetricType {
    DAILY_COMMITS_COUNT, DAILY_COMMITS_AVG_SIZE,
    DAILY_PR_CREATED, DAILY_PR_MERGED,
    DAILY_ISSUES_CREATED, DAILY_ISSUES_CLOSED,
    DAILY_CHURN_RATIO,
    PR_LEAD_TIME_HOURS_MEDIAN,
    ISSUE_LEAD_TIME_HOURS_MEDIAN,
    PR_FIRST_COMMIT_TO_MERGE_LEAD_TIME_HOURS_MEDIAN,
    REVIEW_RESPONSE_TIME_HOURS_MEDIAN,
    FOCUS_RATIO_DAYS_TASKS
}
