package com.juliashtal.devanalytics.config;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.info.BuildProperties;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.web.servlet.MockMvc;

import static org.assertj.core.api.Assertions.assertThat;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

/**
 * Pins the single source of the displayed version: the SPA footer reads it from
 * {@code /actuator/info}, which must answer before login and must report the Maven version
 * rather than a second copy maintained by hand.
 */
@SpringBootTest
@org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc
class BuildVersionEndpointTest {

    @Autowired MockMvc mockMvc;
    @Autowired(required = false) BuildProperties buildProperties;

    @Test
    void info_isReachableWithoutAuthentication_andReportsTheBuildVersion() throws Exception {
        mockMvc.perform(get("/actuator/info"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.build.version").exists());
    }

    @Test
    void buildVersion_comesFromTheMavenProjectVersion() {
        // build-info.properties is generated by the spring-boot-maven-plugin build-info goal;
        // if that execution is dropped the bean disappears and the footer loses its source.
        assertThat(buildProperties).isNotNull();
        assertThat(buildProperties.getVersion()).isNotBlank();
    }
}
